### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by dblock** [dblock/log4jna#10]
https://ci.appveyor.com/project/dblock/log4jna

maybe http://www.yegor256.com/2015/01/10/windows-appveyor-maven.html?

**Comment by claudiow** [comment]
Based on oshi and thinking on having  the dblock projects consistent, what about `https://travis-ci.org/dblock/oshi/` and `https://travis-ci.org/dblock/log4jna/`?

This will enable you to create a `dblock-parent` and keep a consistent set of ci configurations like:
````
<ciManagement>
  <system>travis</system>
  <url>https://travis-ci.org/dblock/oshi/</url>
</ciManagement>
````

BTW can we open a conversation about ci and maven central all together?  Almost all of this can be based from oshi and is related.

**Comment by dblock** [comment]
You can't use Travis because they don't have Windows and I'd love to see tests actually run, that's why I am suggesting AppVeyor. What do you think?

I want you to take some initiative here and try things! Instead of asking for permission ask for forgiveness and it's totally cool to try something, fail, iterate. I'm here to help.

**Comment by claudiow** [comment]
Ok testing is more important than consistency. 

I'm speculating here but I don't see how a 3rd party will allow us to write into the registry to run those test.

Unfortunately this are more integration tests than unit test and you need elevated permissions  to access the registry, most probably the test will fail even in a windows ci environment.

Given that you already have an account with appveyor, Can you contact support and see if they can do anything for us?

I'm investigating if there is a way of mocking the registry write/read process to create unit tests,

**Comment by dblock** [comment]
AppVeyor's builds run with administrative privileges on isolated VMs. Problem solved.

**Comment by claudiow** [comment]
Ok, I created my account in appveyor, 

Can you please add my user **claudiow** to the project.

Also how do I proceed for now on? Do i continue on my fork with a new pull request or do I work in master?

**Comment by dblock** [comment]
I've added you to log4jna, welcome!

You should continue making pull requests, please, even though you have access. You can code review and merge other people's contributions.

Try getting the build running - the pull requests are automatically built when you make/update them.

**Comment by claudiow** [comment]
I cant access [https://ci.appveyor.com/project/dblock/log4jna](https://ci.appveyor.com/project/dblock/log4jna). I think that I can't use my AppVeyor user to see the project, I could not found hoe to do it at AppVeyor site.

In the meantime I'm using [https://ci.appveyor.com/project/claudiow/log4jna](https://ci.appveyor.com/project/claudiow/log4jna).

This is in a very early stage and full of errors that I'm investigating.

**Comment by dblock** [comment]
I don't think you need to access that project or edit it, commit an `appveyor.yml` and do all the config there. If you do it on your fork, you can see it on https://ci.appveyor.com/project/claudiow/log4jna (as you said), if you make pull requests you can see the output in https://ci.appveyor.com/project/dblock/log4jna.
