### ISSUE TITLE
Change the project from org.apache to org.dblock

### ISSUE THREAD

**Issue by dblock** [dblock/log4jna#11]
See https://github.com/dblock/log4jna/pull/9#issuecomment-227850429.

**Comment by claudiow** [comment]
I didn't comment on this as you requested to wait until we have a working build.

Based on `https://github.com/dblock/oshi` I think we should go with `com.github.dblock.log4jna` and keep consistence with all `dblock` projects.

Another advantage is that we do not have to pay for the domain registration and remember to mantain it every yea.

Unless you want to register the domain and protect the log4jna name. I gladly contribute the first year registration fee, but you should be the owner and technical contact.

**Comment by dblock** [comment]
I think we don't need a domain for `log4jna`, it's not that big of a deal, no need to waste 8$ a year :)  I am totally cool with whatever name, `com.github.dblock.log4jna` is perfect. If you want it shorter, I own `dblock.org`, so you could make it `org.dblock`, pick one!

**Comment by claudiow** [comment]
`org.dblock` It is then.

**Comment by claudiow** [comment]
I'm changing the project to org.dblock. We have a repository with Sonatype for the domain see:
`https://issues.sonatype.org/browse/OSSRH-23287`

**Comment by claudiow** [comment]
I'm starting work on this. 
I suggest that we delete the Eclipse configuration files from git 
Those files differ from user to user an create conflicts every time that I update upstream/master in to my fork. On the other hand they are not part of the project, each developer can use the IDE he/she prefer.
Once I have a working build against my own Maven repo I'll test deploying the SNAPSHOT into [https://oss.sonatype.org/content/repositories/snapshots](https://oss.sonatype.org/content/repositories/snapshots)

**Comment by dblock** [comment]
Yes with Maven there's no need to have Eclipse configuration here. Also note https://github.com/dblock/log4jna/issues/12, we should clearly document how to start contributing to this project, including how to setup a basic IDE (Eclipse or whatever).

**Comment by claudiow** [comment]
Project was changed to org.`dblock.log4jna` in the pom this produces [this](https://oss.sonatype.org/content/groups/public/org/dblock/log4jna/) on Maven repositories.

I think we can close this one

**Comment by dblock** [comment]
The code itself is still `package org.apache.log4jna`, I think we want to change all that too to match.

**Comment by claudiow** [comment]
Code packages changed to org.dblock.log4jna in #22

**Comment by dblock** [comment]
Closed via https://github.com/dblock/log4jna/pull/22.
