### ISSUE TITLE
Add RELEASING.md

### ISSUE THREAD

**Issue by dblock** [dblock/log4jna#13]
Add a release instruction document ala https://github.com/dblock/waffle/blob/master/Docs/MavenReleaseGuide.md.

**Comment by dblock** [comment]
/cc: @claudiow As you go through the motions of making a maven central release, cook up and PR a document about how that's setup and how to do it.

**Comment by dblock** [comment]
@claudiow I'd love to see some progress on this and getting a full release into maven central!

**Comment by claudiow** [comment]
I'm almost ready.

Can you please start by reviewing the documentation and site in [https://github.com/claudiow/log4jna/tree/site-development](https://github.com/claudiow/log4jna/tree/site-development)

I will start on the MavenRelease.md later today or tomorrow. Hopping to have it sometime tomorrow.

As we are going to build with CI and the release plugin you will have to add some entries to the settings.xml file. A user id and password for git or a ssh key to allow the maven release:perform to create a tag and check in the modified pom.xml files back into master.

The instructions for waffle are for build and deploy from a local machine and assumes that you are building from a local fork.

Bearing in mind that release to Maven Central can't be deleted we have to do it right the very first time. That is why I'm taking a lot of time testing in my local Build and Deploy environment.

**Comment by claudiow** [comment]
To review the site, checkout the branch and run `mvn site site:stage` you can browse the site in `log4jna\target\staging\index.html

**Comment by dblock** [comment]
It looks great!

Bad builds can be replaced with better builds :)

**Comment by claudiow** [comment]
That would increment the version number or require to check out master change the version back and delete t he tag.

I'll try to get something ready by tomorrow or the day after.

**Comment by dblock** [comment]
Closed via https://github.com/dblock/log4jna/pull/39.
