### ISSUE TITLE
Replace dependabot with renovate

### ISSUE THREAD

**Issue by dblock** [dblock/log4jna#157]
Dependabot opens 10+ PRs for maven dependencies given the number of config files in this repo.

Replace with https://github.com/renovatebot/renovate that can do this in one go.

![Screenshot 2023-03-28 at 9 48 47 AM](https://user-images.githubusercontent.com/542335/228259132-26959f3d-58a4-4920-b552-d74818f44d95.png)

**Comment by yokra9** [comment]
Dependabot Grouped Updates will come in Q2 2023 (Apr-Jun) in GitHub public roadmap :)

> Update: We've started doing some grouped updates work! This particular issue might not be part of the first ship but if you want to track our updates, do follow https://github.com/dependabot/dependabot-core/issues/1190.
https://github.com/dependabot/dependabot-core/issues/1595#issuecomment-1496633342

**Comment by yokra9** [comment]
[Grouped updates for Dependabot version updates is officially GA](https://github.blog/changelog/2023-08-24-grouped-version-updates-for-dependabot-are-generally-available/), but there isn't any way to create 1 PR for the same update across `update-configs`. I sent feedback to GitHub and received blow message:

> Today, we do not have the ability to group across update-configs. We are looking at this for a future release, but I don't know exactly when yet.
