### ISSUE TITLE
Publish the Maven site to gh-pages

### ISSUE THREAD

**Issue by claudiow** [dblock/log4jna#20]
I noticed that OSHI publishes the Maven site to [http://dblock.github.io/oshi/](http://dblock.github.io/oshi/)

Can we get access to a new directory there like http://dblock.github.io/log4jna/ and instructions on how to upload to the site.

**Comment by dblock** [comment]
This is basically automatically setup if there's a `gh-pages` branch in the project, the output of the build should be dumped into that and I can tick a box to enable it.

**Comment by claudiow** [comment]
That looks fine. There is even a Maven plugin to publish to the gh-pages branch.

Lets see if I can test that from my fork before exposing it in the main project.

**Comment by dblock** [comment]
Renamed this to _Publish the maven site to gh-pages_ to reflect what we want.

**Comment by dblock** [comment]
Closed via https://github.com/dblock/log4jna/pull/39.
