### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by zbrkic** [dblock/log4jna#237]
When I try to download from main page, username and password are required. What username and password should be used?

**Comment by dblock** [comment]
Looks like the links are broken. It should be something like https://oss.sonatype.org/service/local/repositories/releases/content/org/dblock/log4jna/log4jna-api/2.1.0/log4jna-api-2.1.0.jar

Care to fix them please? Make a PR?

**Comment by dblock** [comment]
https://github.com/dblock/log4jna/pull/242
