### ISSUE TITLE
Build is failing on dblock/log4jna

### ISSUE THREAD

**Issue by dblock** [dblock/log4jna#32]
@claudiow Do I just need to change the secret value? Anything else?

**Comment by claudiow** [comment]
No it looks that the decrypt instruction is not working.

I've been looking at this and it will take me some time to pin the exact error

**Comment by claudiow** [comment]
Fixed in #32
Some how the constants for the file names got screwed in the last merge

**Comment by claudiow** [comment]
You can comment my secret and uncomment yours in the apveyor.yml or check your master build in my environment here [https://ci.appveyor.com/project/claudiow/log4jna-7o8kf](https://ci.appveyor.com/project/claudiow/log4jna-7o8kf) after you merge.

**Comment by dblock** [comment]
Fixed via https://github.com/dblock/log4jna/pull/36.
