### ISSUE TITLE
Logs go into the wrong location in EventViwer after Changing configuration

### ISSUE THREAD

**Issue by claudiow** [dblock/log4jna#37]
If a Key for **Source** with the same name exists in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\` and `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\<any-other-name>\` 

Logging will continue to go into 'Application--<source-name>' until the key is deleted in the registry.

Reproduction steps:
1. Crate a Log4j2 configuration with `application=Application` and `source=WinLogger`
2. Run the NewDemo application 
   1. Logging appears in `EventViewer->Windows Logs->Application` with a 'Source=WinLogger`
3. Change the configuration to `application=Win32LogApplication`
4. Run the NewDemo application
   1. `EventLogger->Application and Service Logs->Win32LogApplication`  is created
   2. But the logs continue to go into `EventViewer->Windows Logs->Application` with a 'Source=WinLogger`

Today the code only checks for changes in the message file location and updates the registry.

Proposed solution: add checks for changes in `application` and `source` configuration parameters and delete / create keys as needed in the registry.

This solution has the caveat that if 2 applications have different 'application' and the same 'source' Log4JNA will be deleting and creating the keys continuously and the logging will be too slow.

Another solution is to throw a run time exception advertising the configuration conflict and by pass the log until the `source` configuration conflict is resolved.

**Comment by claudiow** [comment]
Other side effects of the sae situation: If you have 2 applications in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\<any-other-name>\` with 2 different `source` configuration parameters, only the first run is created.

The code does not check for changes in the configuration only tests that  `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\<any-other-name>\` exists and assumes that everything is set up.

**Comment by claudiow** [comment]
Further investigation:

Any change to the registry after initial `source` key creation requires a Windows restart to take effect.

This can e problematic for Web Applications using the logger.

**Comment by claudiow** [comment]
I can confirm that this is a 2 fold issue.

1. If the application is already running and the handle for the event source was already acquired the registry will not be updated.
2. If the configuration change happens in a root key that already exist at application start up, the change will not take effect until system restart (apparently the Event Log service does not reloads the keys.

The writing of the keys to the registry is an easy fix.

A second source of possible questions from users is that we will not support configuration changes on Log4J 2 configuration auto reload as the application will not be running as Administratior.

We will need an entry in the FAQ for this situations.

We can also take advantage of Log4J 2 LOGGER to send logs instead of only throwing the Win32Exception run time exception. This log could always end with something like "Are you running as Administrator." and give the users a hint of what is happening.

The issue is that Log4j 2 supports configuration reload and users or administrator might assume that th

**Comment by claudiow** [comment]
Daniel, can we close this one, We know that the changes do not take effect until a Windows restart and there is little we can do.

**Comment by dblock** [comment]
Sure, you can too :)
