### ISSUE TITLE
Image links in USAGE.md are broken

### ISSUE THREAD

**Issue by RedShift1** [dblock/log4jna#40]
In page https://github.com/dblock/log4jna/blob/master/USAGE.md#registry

https://github.com/dblock/log4jna/blob/master/scr/site/resources/img/registry1.png
and
https://github.com/dblock/log4jna/blob/master/scr/site/resources/img/registry2.png

don't exist anymore.

**Comment by claudiow** [comment]
The images still are in the `src/site/resources/img/` directory.

Daniel can you check the syntax in lines 222 and 232 of USAGE.md?

`![Registry Img](src/site/resources/img/registry1.png)` Translates to `https://github.com/dblock/log4jna/blob/master/scr/site/resources/img/registry1.png` I can't figure out what is wrong why is the MD processor not seen the images, when you click on them they show properly.

The same happens with on the gh-pages branch

**Comment by dblock** [comment]
Would someone please PR a fix? Thanks.

**Comment by dblock** [comment]
@yokra9 Want to take care of this one too?

**Comment by yokra9** [comment]
I'll create a new workflow to enable the `maven-scm-publish-plugin`.

In my fork repo, it seems to work fine :)
https://yokra9.github.io/log4jna/USAGE.html
https://github.com/yokra9/log4jna/actions/runs/2184071089
https://github.com/yokra9/log4jna/commits/gh-pages

Please set secrets for this repository
`CONTRIBUTOR_USERNAME`: your GitHub UserName
`CONTRIBUTOR_TOKEN`: your [Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)

**Comment by dblock** [comment]
Do we really need a PAT here, can't `${{ secrets.GITHUB_TOKEN }}`, potentially with [custom permissions](https://dev.to/github/the-githubtoken-in-github-actions-how-it-works-change-permissions-customizations-3cgp) work here? Let's give it a try?

**Comment by yokra9** [comment]
The `maven-scm-publish-plugin` requires a username and password. @claudiow set his username and password in an encrypted setting file, but [we need to set PAT instead of password nowadays](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/).

I tried setting only `GITHUB_TOKEN` as the password, but [the workflow failed because of the username absence](https://github.com/yokra9/log4jna/actions/runs/2184646622).

**Comment by dblock** [comment]
I set `GIT_USERNAME` to `dblock`, and `GIT_ACCESS_TOKEN` to a PAT.

**Comment by yokra9** [comment]
It seems to work fine.
https://github.com/dblock/log4jna/actions/runs/2190752088
https://github.com/dblock/log4jna/actions/runs/2190772135
http://dblock.github.io/log4jna/USAGE.html
