### ISSUE TITLE
ToDo: `log4jna` v2.1 Release

### ISSUE THREAD

**Issue by yokra9** [dblock/log4jna#47]
- [x] Updating project version to 2.1.0-SNAPSHOT ac99aa81b6bd76f76f303cdf275341e9d17bae2f
- [x] Updating CHANGELOG
- [x] #57 
- [x] #50 
- [x] #42 ( #84 )
- [x] #40

**Comment by yokra9** [comment]
@dblock [There seems to have been AppVeyor Project `Log4JNA Release`, which could release on maven central](https://github.com/dblock/log4jna/blob/master/AppVeyorMavenRelease.md). What do you remember about this project?

**Comment by dblock** [comment]
Yep, but @claudiow set all this up and I don't think he's around anymore. It's all well documented it seems tho.

**Comment by yokra9** [comment]
I understand. I'll create new appveyor projects, and invite you as administrator just in case.

**Comment by dblock** [comment]
> I understand. I'll create new appveyor projects, and invite you as administrator just in case.

You shouldn't need that! I do have access to all the things. LMK what you need?

**Comment by yokra9** [comment]
Oh, I mistakenly assumed that you had lost contact with the administrator and could no longer control `Log4JNA Release` project. When I help to release v2.1 to Maven Central, I think I'll be asking you to click build button on the project.

**Comment by dblock** [comment]
Cool. Can I get you to click on the button? what kind of permissions do you need? I had already invited you to collaborate here

**Comment by yokra9** [comment]
1. LMK `Log4JNA Release` Project URL to access.

2. PLS invite me as Administrator Role on Appveyor Team. I think I’ll be granted to control project. My E-Mail address is yokra9[at]outlook.com

![image](https://user-images.githubusercontent.com/53964890/136177771-afe6f426-a388-4b95-b7d9-4f4580873191.png)

**Comment by dblock** [comment]
@yokra9 I don't have that team button in https://ci.appveyor.com/project/dblock/log4jna, but I do seem to have Admin rights. Does it mean we forever lost access to enable adding people to that project? It's strange, I can delete the project and such, are you sure it's managed via that "team" for GitHub projects?

<img width="1054" alt="Screen Shot 2021-10-06 at 10 04 59 AM" src="https://user-images.githubusercontent.com/542335/136218741-3f2c58b0-2ac0-4b65-aaf1-3d6dbfe1c005.png">

**Comment by dblock** [comment]
🤷 I don't see more than you. But I think you're right - I don't see any historical deployments in https://ci.appveyor.com/project/dblock/log4jna.

It's weird to have a release project elsewhere than under /dblock since it's /dblock on GitHub, but lmk what I can do?

**Comment by yokra9** [comment]
Build failed. The cause may be environment variable `secret`, which is encrypted variable. 
https://www.appveyor.com/docs/appveyor-yml/
https://ci.appveyor.com/account/dblock/tools/encrypt

On `appveyor-mvn-release.yml`, there are 2 `secret`. one is valid values, and the other is commented out. 

https://github.com/dblock/log4jna/blob/master/appveyor-mvn-release.yml

I think the former is encrypted by claudiow's account, and latter may be done by yours. I'll send PR to replace them.

**Comment by dblock** [comment]
I have a password, I think. How do I verify that it's valid?

**Comment by dblock** [comment]
Having some difficulties between the computer and the chair for this, e-mailed what I had to you.

**Comment by yokra9** [comment]
To confirm environment variable is set, Could I add next statement at yaml file?

```
Write-Host `$env:secret is $env:secret
```

I think the secure value will be masked at appveyor console, like this.

https://ci.appveyor.com/project/yokra9/log4jna-sample/builds/41117361#L18

**Comment by dblock** [comment]
@yokra9 Did you give up on this?

**Comment by yokra9** [comment]
I gave up on fixing #49 and will try to migrate from AppVeyor to GitHub Actions on new PR.

**Comment by yokra9** [comment]
It has been a month without a reply from @claudiow. 

How about distributing v2.1 onwards at `com.github.dblock.log4jna` instead of `org.dblock.log4jna`? I think you have credentials of `com.github.dblock`.

**Comment by dblock** [comment]
> It has been a month without a reply from @claudiow.
> 
> How about distributing v2.1 onwards at `com.github.dblock.log4jna` instead of `org.dblock.log4jna`? I think you have credentials of `com.github.dblock`.

I opened https://issues.sonatype.org/browse/OSSRH-79529 to try and recover access to the Log4JNACI account. If not we can always create another account and ask to give that access to `org.dblock.log4jna`, since I definitely have access to that.

**Comment by dblock** [comment]
The password has been changed and @yokra9 and @twall have it in case anyone else ever needs it and I am not around.

**Comment by dblock** [comment]
RIP @claudiow https://passages.winnipegfreepress.com/passage-details/id-273651/TRAJTENBERG_CLAUDIO

**Comment by yokra9** [comment]
> The password has been changed and @yokra9 and @twall have it in case anyone else ever needs it and I am not around.

RIP @claudiow, and thanks for resetting the password.
Next, please set secrets for a user account repository. The repository owner only can set secrets for a user account repository. 

`MAVEN_CENTRAL_TOKEN`: password of OSSHR account Log4JNACI
`MAVEN_GPG_PRIVATE_KEY`: GPG private key
`MAVEN_GPG_PASSPHRASE`: GPG private key passphrase
https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository

**Comment by dblock** [comment]
@yokra9 Done. I'll also email you copies.

**Comment by yokra9** [comment]
I pushed this commit. The `Deploy` action failed.

https://github.com/dblock/log4jna/actions/runs/2142862588

Building and signing the artifacts was successful, but uploading failed due to `401 Unauthorized`.

> Error:  Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7:deploy (injected-nexus-deploy) on project log4jna-assembly: Failed to deploy artifacts: Could not transfer artifact org.dblock.log4jna:log4jna-demo:jar:javadoc:2.0.1-20220410.045443-2 from/to osshr (https://oss.sonatype.org/content/repositories/snapshots): authentication failed for https://oss.sonatype.org/content/repositories/snapshots/org/dblock/log4jna/log4jna-demo/2.0.1-SNAPSHOT/log4jna-demo-2.0.1-20220410.045443-2-javadoc.jar, status: 401 Unauthorized -> [Help 1]


Can you think of any reasons for failure?

**Comment by dblock** [comment]
Fixed it in https://github.com/dblock/log4jna/commit/047725390ed08535113df2063967822cd6cbb3da and https://github.com/dblock/log4jna/actions/runs/2177055669

We had some variable name disagreement, I had actually set OSSRH_USERNAME and OSSRH_PASSWORD 🤦 

Want to cleanup old AppVeyor stuff, make a release workflow and PR into main?

(And huge thanks for hanging in here and helping with this!)

**Comment by yokra9** [comment]
Thank you for fixing the OSSRH settings!
I created release workflow and PR into master.

> (And huge thanks for hanging in here and helping with this!)

I'm glad at to contribute to your helpful OSS. Could I add my name as a developer in pom.xml?

**Comment by dblock** [comment]
> Thank you for fixing the OSSRH settings! I created release workflow and PR into master.
> 
> > (And huge thanks for hanging in here and helping with this!)
> 
> I'm glad at to contribute to your helpful OSS. Could I add my name as a developer in `pom.xml`?

Yes please!

Make a release as you see fit.

**Comment by yokra9** [comment]
We solved all items of this ToDo!
I'll run `Log4JNA Release` action and deploy the artifacts to Sonatype's staging repository.

**Comment by dblock** [comment]
We are using `secrets.GIT_ACCESS_TOKEN`, I think the default `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` should work, no?

**Comment by yokra9** [comment]
> We are using `secrets.GIT_ACCESS_TOKEN`, I think the default `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` should work, no?

`GITHUB_USERNAME` and `GITHUB_TOKEN` are [used for maven-scm-publish-plugin as username and password](https://github.com/dblock/log4jna/issues/40#issuecomment-1101518092).
maven-release-plugin also needs credentials, probably on another way.

**Comment by dblock** [comment]
Fixed in https://github.com/dblock/log4jna/commit/c7475ebb0c12383e022e0afe18795fb661851a7a, release workflow ran!

**Comment by dblock** [comment]
I released the staging repo, and [updated CHANGELOG](https://github.com/dblock/log4jna/commit/17fca338693ee1209625034a9334fad77b12074b). Opened #91.

I think we're done with 2.1.0!
