### ISSUE TITLE
Log4jna 2.0 not compatible with JNA 5.10

### ISSUE THREAD

**Issue by TaylorAtTempus** [dblock/log4jna#52]
When attempting to use Log4jna in an application with JNA 5.10 specified, I get the following error: 
`ERROR An exception occurred processing Appender Win32EventLog org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.NoSuchFieldError: SIZE`

Moving to version 4.5.2 of JNA resolved the issue, but since at least in Maven's repository it is marked as compatible with every version up to the latest, I wonder if there is a warning you can include here somewhere to give people a heads-up.
(I tracked this down from a comment on a different project with a similar error: https://github.com/MarkusBernhardt/proxy-vole/issues/73)

**Comment by dblock** [comment]
Do we need to upgrade? I just merged https://github.com/dblock/log4jna/pull/50

I am not actively working on this or using it, but happy to help in any way I can.

**Comment by TaylorAtTempus** [comment]
That looks like it fixed it.  Thank you :)
